/*
 * spamapi
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveSpamapiClient);
  }
}(this, function(expect, CloudmersiveSpamapiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SpamDetectionAdvancedResponse', function() {
      beforeEach(function() {
        instance = new CloudmersiveSpamapiClient.SpamDetectionAdvancedResponse();
      });

      it('should create an instance of SpamDetectionAdvancedResponse', function() {
        // TODO: update the code to test SpamDetectionAdvancedResponse
        expect(instance).to.be.a(CloudmersiveSpamapiClient.SpamDetectionAdvancedResponse);
      });

      it('should have the property cleanResult (base name: "CleanResult")', function() {
        // TODO: update the code to test the property cleanResult
        expect(instance).to.have.property('cleanResult');
        // expect(instance.cleanResult).to.be(expectedValueLiteral);
      });

      it('should have the property containsSpam (base name: "ContainsSpam")', function() {
        // TODO: update the code to test the property containsSpam
        expect(instance).to.have.property('containsSpam');
        // expect(instance.containsSpam).to.be(expectedValueLiteral);
      });

      it('should have the property containsUnsolicitedSales (base name: "ContainsUnsolicitedSales")', function() {
        // TODO: update the code to test the property containsUnsolicitedSales
        expect(instance).to.have.property('containsUnsolicitedSales');
        // expect(instance.containsUnsolicitedSales).to.be(expectedValueLiteral);
      });

      it('should have the property containsPromotionalContent (base name: "ContainsPromotionalContent")', function() {
        // TODO: update the code to test the property containsPromotionalContent
        expect(instance).to.have.property('containsPromotionalContent');
        // expect(instance.containsPromotionalContent).to.be(expectedValueLiteral);
      });

      it('should have the property containsPhishingAttempt (base name: "ContainsPhishingAttempt")', function() {
        // TODO: update the code to test the property containsPhishingAttempt
        expect(instance).to.have.property('containsPhishingAttempt');
        // expect(instance.containsPhishingAttempt).to.be(expectedValueLiteral);
      });

    });
  });

}));
