/*
 * spamapi
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveSpamapiClient);
  }
}(this, function(expect, CloudmersiveSpamapiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveSpamapiClient.SpamDetectionApi();
  });

  describe('(package)', function() {
    describe('SpamDetectionApi', function() {
      describe('spamDetectTextStringAdvancedPost', function() {
        it('should call spamDetectTextStringAdvancedPost successfully', function(done) {
          // TODO: uncomment, update parameter values for spamDetectTextStringAdvancedPost call and complete the assertions
          /*
          var opts = {};
          opts.body = new CloudmersiveSpamapiClient.SpamDetectionAdvancedRequest();
          opts.body.inputString = "";
          opts.body.model = "";
          opts.body.allowUnsolicitedSales = false;
          opts.body.allowPromotionalContent = false;
          opts.body.allowPhishing = false;

          instance.spamDetectTextStringAdvancedPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveSpamapiClient.SpamDetectionAdvancedResponse);
            expect(data.cleanResult).to.be.a('boolean');
            expect(data.cleanResult).to.be(false);
            expect(data.containsSpam).to.be.a('boolean');
            expect(data.containsSpam).to.be(false);
            expect(data.containsUnsolicitedSales).to.be.a('boolean');
            expect(data.containsUnsolicitedSales).to.be(false);
            expect(data.containsPromotionalContent).to.be.a('boolean');
            expect(data.containsPromotionalContent).to.be(false);
            expect(data.containsPhishingAttempt).to.be.a('boolean');
            expect(data.containsPhishingAttempt).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('spamDetectTextStringPost', function() {
        it('should call spamDetectTextStringPost successfully', function(done) {
          // TODO: uncomment, update parameter values for spamDetectTextStringPost call and complete the assertions
          /*
          var opts = {};
          opts.body = new CloudmersiveSpamapiClient.SpamDetectionRequest();
          opts.body.inputString = "Get free crypto now!!!";
          opts.body.model = "Advanced";

          instance.spamDetectTextStringPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveSpamapiClient.SpamDetectionResponse);
            expect(data.cleanResult).to.be.a('boolean');
            expect(data.cleanResult).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
