/*
 * spamapi
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveSpamapiClient) {
      root.CloudmersiveSpamapiClient = {};
    }
    root.CloudmersiveSpamapiClient.SpamDetectionAdvancedResponse = factory(root.CloudmersiveSpamapiClient.ApiClient, root.CloudmersiveSpamapiClient.ModelObject);
  }
}(this, function(ApiClient, ModelObject) {
  'use strict';

  /**
   * The SpamDetectionAdvancedResponse model module.
   * @module model/SpamDetectionAdvancedResponse
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>SpamDetectionAdvancedResponse</code>.
   * Result of detecting spam using AI
   * @alias module:model/SpamDetectionAdvancedResponse
   * @class
   * @extends Object
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SpamDetectionAdvancedResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SpamDetectionAdvancedResponse} obj Optional instance to populate.
   * @return {module:model/SpamDetectionAdvancedResponse} The populated <code>SpamDetectionAdvancedResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ModelObject');
      if (data.hasOwnProperty('CleanResult'))
        obj.cleanResult = ApiClient.convertToType(data['CleanResult'], 'Boolean');
      if (data.hasOwnProperty('ContainsSpam'))
        obj.containsSpam = ApiClient.convertToType(data['ContainsSpam'], 'Boolean');
      if (data.hasOwnProperty('ContainsUnsolicitedSales'))
        obj.containsUnsolicitedSales = ApiClient.convertToType(data['ContainsUnsolicitedSales'], 'Boolean');
      if (data.hasOwnProperty('ContainsPromotionalContent'))
        obj.containsPromotionalContent = ApiClient.convertToType(data['ContainsPromotionalContent'], 'Boolean');
      if (data.hasOwnProperty('ContainsPhishingAttempt'))
        obj.containsPhishingAttempt = ApiClient.convertToType(data['ContainsPhishingAttempt'], 'Boolean');
    }
    return obj;
  }

  /**
   * True if the result is not spam (clean), and false otherwise
   * @member {Boolean} cleanResult
   */
  exports.prototype.cleanResult = undefined;

  /**
   * True if the input text contains spam, false otherwise
   * @member {Boolean} containsSpam
   */
  exports.prototype.containsSpam = undefined;

  /**
   * True if the input text contains unsolicited sales, false otherwise
   * @member {Boolean} containsUnsolicitedSales
   */
  exports.prototype.containsUnsolicitedSales = undefined;

  /**
   * True if the input text contains promotional content, false otherwise
   * @member {Boolean} containsPromotionalContent
   */
  exports.prototype.containsPromotionalContent = undefined;

  /**
   * True if the input text contains a phishing attempt, false otherwise
   * @member {Boolean} containsPhishingAttempt
   */
  exports.prototype.containsPhishingAttempt = undefined;

  exports.prototype.additionalProperties = new Map();

  return exports;

}));
