/*
 * spamapi
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveSpamapiClient) {
      root.CloudmersiveSpamapiClient = {};
    }
    root.CloudmersiveSpamapiClient.SpamDetectionRequest = factory(root.CloudmersiveSpamapiClient.ApiClient, root.CloudmersiveSpamapiClient.ModelObject);
  }
}(this, function(ApiClient, ModelObject) {
  'use strict';

  /**
   * The SpamDetectionRequest model module.
   * @module model/SpamDetectionRequest
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>SpamDetectionRequest</code>.
   * AI spam detection request
   * @alias module:model/SpamDetectionRequest
   * @class
   * @extends Object
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SpamDetectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SpamDetectionRequest} obj Optional instance to populate.
   * @return {module:model/SpamDetectionRequest} The populated <code>SpamDetectionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ModelObject');
      if (data.hasOwnProperty('InputString'))
        obj.inputString = ApiClient.convertToType(data['InputString'], 'String');
      if (data.hasOwnProperty('Model'))
        obj.model = ApiClient.convertToType(data['Model'], 'String');
    }
    return obj;
  }

  /**
   * Input text string to detect spam against
   * @member {String} inputString
   */
  exports.prototype.inputString = undefined;

  /**
   * Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
   * @member {String} model
   */
  exports.prototype.model = undefined;

  exports.prototype.additionalProperties = new Map();

  return exports;

}));
